name: cppcheck
on: [push]
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update -q &&
          sudo apt install -y cppcheck
      - name: cppcheck dstd
        run: |
          cppcheck --inline-suppr --error-exitcode=1 --language=c++ --enable=all -I ./dstd/include/ ./dstd/src/ --suppress=unusedFunction
      - name: cppcheck kernel
        run: |
          cppcheck --inline-suppr --error-exitcode=1 --language=c++ --enable=all -I ./dstd/include/ -I ./kernel/include/ ./kernel/src/
