name: cppcheck
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update -q &&
          sudo apt install -y cppcheck
      - name: cppcheck dstd
        run: |
          cppcheck -j $(nproc) --error-exitcode=1 --language=c++ --enable=all -I ./dstd/include/ ./dstd/src/
      - name: cppcheck kernel
        run: |
          cppcheck -j $(nproc) --error-exitcode=1 --language=c++ --enable=all -I ./dstd/include/ -I ./kernel/include/ ./kernel/src/
