name: unit tests
on: [push]
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update -q &&
          sudo apt install -y clang cmake lld-12 ninja-build nasm &&
          sudo ln -s /usr/bin/ld.lld-12 /usr/bin/ld.lld
      - name: run cmake
        run: |
          cmake . -B build -G Ninja -DBUILD_KERNEL=OFF -DBUILD_TESTS=ON
      - name: run ninja
        run:  |
          ninja -C build
      - name: run tests
        run: ./build/tests/tests  
