name: valgrind
on:
  workflow_run:
    workflows: ["unit tests"]
    types:
    - completed
jobs:
  valgrind:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update -q &&
          sudo apt install -y clang cmake lld-12 ninja-build nasm valgrind &&
          sudo ln -s /usr/bin/ld.lld-12 /usr/bin/ld.lld
      - name: run cmake
        run: |
          mkdir build &&
          cd build &&
          cmake .. -G Ninja -DBUILD_KERNEL=OFF -DBUILD_TESTS=ON
      - name: run ninja
        run: |
          cd build &&
          ninja
      - name: run valgrind
        run: |
          valgrind --show-error-list=yes ./tests/tests
